## Model Training

#### 1.1 Import Data and Required Packages
##### Importing Pandas, Numpy, Matplotlib, Seaborn and Warings Library.

In [5]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

#### Import the CSV Data as Pandas DataFrame

In [6]:
df = pd.read_csv('E:\\zomato_project\\notebook\\data\\Realzomatodata.csv')

#### Show Top 5 Records

In [7]:
df.head()

,Delivery_person_Age,Delivery_person_Ratings,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),Time_Orderd_minute,Time_Orderd_second,Time_Order_picked_minute,Time_Order_picked_second
0,36.0,4.2,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,21.0,55.0,22.0,10.0
1,21.0,4.7,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,14.0,55.0,15.0,5.0
2,23.0,4.7,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,17.0,30.0,17.0,40.0
3,34.0,4.3,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,9.0,20.0,9.0,30.0
4,24.0,4.7,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,19.0,50.0,20.0,5.0

In [6]:
# # import pandas as pd

# # # Load your dataset
# # df = pd.read_csv("your_dataset.csv")

# # Convert "Time_Orderd" and "Time_Order_picked" to datetime
# # Set the format argument to mm:ss (minutes:seconds)
# df['Time_Orderd'] = pd.to_datetime(df['Time_Orderd'], format='%M:%S')
# df['Time_Order_picked'] = pd.to_datetime(df['Time_Order_picked'], format='%M:%S')

# # Extract minute and second features
# df['Time_Orderd_minute'] = df['Time_Orderd'].dt.minute
# df['Time_Orderd_second'] = df['Time_Orderd'].dt.second

# df['Time_Order_picked_minute'] = df['Time_Order_picked'].dt.minute
# df['Time_Order_picked_second'] = df['Time_Order_picked'].dt.second

# # Now your dataframe should have minute and second columns extracted from time columns
# # You can then proceed to use this processed data for modeling

In [8]:
df

,Delivery_person_Age,Delivery_person_Ratings,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),Time_Orderd_minute,Time_Orderd_second,Time_Order_picked_minute,Time_Order_picked_second
0,36.0,4.2,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,21.0,55.0,22.0,10.0
1,21.0,4.7,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,14.0,55.0,15.0,5.0
2,23.0,4.7,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,17.0,30.0,17.0,40.0
3,34.0,4.3,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,9.0,20.0,9.0,30.0
4,24.0,4.7,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,19.0,50.0,20.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35813,30.0,4.8,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32,11.0,35.0,11.0,45.0
35814,21.0,4.6,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36,19.0,55.0,20.0,10.0
35815,30.0,4.9,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16,23.0,50.0,24.0,5.0
35816,20.0,4.7,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26,13.0,35.0,13.0,40.0
35817,23.0,4.9,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36,17.0,10.0,17.0,15.0

In [200]:
# # Remove rows with any null values
# df.dropna(inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35818 entries, 0 to 35817
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delivery_person_Age       35643 non-null  float64
 1   Delivery_person_Ratings   35602 non-null  float64
 2   Weather_conditions        35818 non-null  object
 3   Road_traffic_density      35818 non-null  object
 4   Vehicle_condition         35818 non-null  int64
 5   Type_of_order             35818 non-null  object
 6   Type_of_vehicle           35818 non-null  object
 7   multiple_deliveries       35049 non-null  float64
 8   Festival                  35640 non-null  object
 9   City                      34880 non-null  object
 10  Time_taken (min)          35818 non-null  int64
 11  Time_Orderd_minute        35818 non-null  float64
 12  Time_Orderd_second        35818 non-null  float64
 13  Time_Order_picked_minute  35818 non-null  float64
 14  Time_Order_picked_second  35818 non-null  float64
dtypes: float64(7), int64(2), object(6)
memory usage: 4.1+ MB

In [10]:
X = df.drop(columns=['Time_taken (min)'],axis=1)   # iv

In [11]:
y = df['Time_taken (min)']

In [12]:
# Define which columns should be ordinal-encoded and which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [14]:
numerical_cols

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Vehicle_condition',
       'multiple_deliveries', 'Time_Orderd_minute', 'Time_Orderd_second',
       'Time_Order_picked_minute', 'Time_Order_picked_second'],
      dtype='object')

In [13]:
categorical_cols

Index(['Weather_conditions', 'Road_traffic_density', 'Type_of_order',
       'Type_of_vehicle', 'Festival', 'City'],
      dtype='object')

In [238]:
Weather_conditions_categories = ['Sunny', 'Cloudy', 'Windy', 'Sandstorms', 'Stormy', 'Fog']
Road_traffic_density_categories = ['Low', 'Medium', 'High', 'Jam']
Type_of_order_categories = ['Drinks', 'Snack', 'Meal', 'Buffet']
Type_of_vehicle_categories = ['electric_scooter', 'motorcycle', 'scooter']
Festival_categories = ['No', 'Yes' ]  # Include nan for missing values
City_categories = ['Metropolitian', 'Urban', 'Semi-Urban']  # Include nan for missing values

In [239]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [240]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),       # for mum we handle null val 
    ('scaler',StandardScaler())                         #we scaling it in standard form 

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinalencoder',OrdinalEncoder(categories=[Weather_conditions_categories, Road_traffic_density_categories, Type_of_order_categories, Type_of_vehicle_categories, Festival_categories, City_categories
])),
    ('scaler',StandardScaler())                             # after ordinalencoder we get num data tht we convert it into standarscaling 
    ]

)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])

In [247]:
X_train

,num_pipeline__Delivery_person_Age,num_pipeline__Delivery_person_Ratings,num_pipeline__Vehicle_condition,num_pipeline__multiple_deliveries,num_pipeline__Time_Orderd_minute,num_pipeline__Time_Orderd_second,num_pipeline__Time_Order_picked_minute,num_pipeline__Time_Order_picked_second,cat_pipeline__Weather_conditions,cat_pipeline__Road_traffic_density,cat_pipeline__Type_of_order,cat_pipeline__Type_of_vehicle,cat_pipeline__Festival,cat_pipeline__City
0,-0.797150,1.164582,-1.219097,0.432770,0.319383,0.315255,0.293744,0.414745,0.866589,1.295120,0.464716,-0.431012,-0.141479,-0.530873
1,-1.494278,-0.436085,1.227097,0.432770,-0.123820,0.678027,-0.148450,1.429101,-0.306265,-0.314001,0.464716,1.261443,-0.141479,-0.530873
2,0.248542,0.524315,-1.219097,0.432770,-0.788625,-1.135832,-0.811741,-0.599610,1.453017,0.490560,0.464716,-0.431012,-0.141479,-0.530873
3,0.074260,0.204182,1.227097,-1.320124,0.540985,-0.047517,0.514840,0.414745,-0.892692,1.295120,0.464716,1.261443,-0.141479,-0.530873
4,0.422824,0.204182,0.004000,0.432770,-2.118235,0.315255,-2.138323,0.752864,0.866589,-1.118561,-1.335972,-0.431012,-0.141479,-0.530873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25067,-0.797150,-3.637418,1.227097,2.185665,1.205790,-1.498604,1.178131,-0.599610,-1.479119,-1.118561,-1.335972,1.261443,7.068193,-0.530873
25068,-1.319996,0.524315,-1.219097,0.432770,-1.675032,0.315255,-1.696129,1.090982,-0.892692,-1.118561,1.365059,-0.431012,-0.141479,-0.530873
25069,0.597106,1.164582,-1.219097,2.185665,0.097782,0.678027,0.072647,1.090982,0.280162,-0.314001,1.365059,-0.431012,-0.141479,-0.530873
25070,0.248542,0.204182,0.004000,0.432770,-1.453430,0.678027,-1.475032,1.429101,1.453017,0.490560,1.365059,-0.431012,-0.141479,-0.530873
25071,-1.145714,1.164582,1.227097,0.432770,-1.453430,-1.135832,-1.475032,-0.599610,-1.479119,0.490560,-1.335972,1.261443,-0.141479,1.810384

In [241]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=30)

In [242]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [243]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [244]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [245]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "CatBoosting Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 6.5158
- Mean Absolute Error: 5.1575
- R2 Score: 0.5177
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.5723
- Mean Absolute Error: 5.2199
- R2 Score: 0.5104
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 6.9774
- Mean Absolute Error: 5.5694
- R2 Score: 0.4470
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.0221
- Mean Absolute Error: 5.6098
- R2 Score: 0.4411
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 6.5158
- Mean Absolute Error: 5.1575
- R2 Score: 0.5177
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.5723
- Mean Absolute Error: 5.2199
- R2 Score: 0.5104
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 4.9228
- Mean Absolute Error: 3.8022
- R2 Score: 0.7247
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.1017
- Mean Absolute Error: 4.7290
- R2 Score: 0.5780
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.1121
- Mean Absolute Error: 0.0037
- R2 Score: 0.9999
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.6575
- Mean Absolute Error: 4.9504
- R2 Score: 0.4977
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 1.8510
- Mean Absolute Error: 1.4185
- R2 Score: 0.9611
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.9155
- Mean Absolute Error: 3.8033
- R2 Score: 0.7262
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 4.1378
- Mean Absolute Error: 3.1945
- R2 Score: 0.8055
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.8238
- Mean Absolute Error: 3.7821
- R2 Score: 0.7363
===================================


CatBoosting Regressor
Model performance for Training set
- Root Mean Squared Error: 4.3503
- Mean Absolute Error: 3.3862
- R2 Score: 0.7850
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.7535
- Mean Absolute Error: 3.7354
- R2 Score: 0.7439
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 6.2724
- Mean Absolute Error: 5.1668
- R2 Score: 0.5531
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.3054
- Mean Absolute Error: 5.1861
- R2 Score: 0.5494
===================================

In [229]:
# RandomForestRegressor() 

lin_model =  RandomForestRegressor() 
lin_model = lin_model.fit(X_train, y_train)
y_pred = lin_model.predict(X_test)
score = r2_score(y_test, y_pred)*100
print(" Accuracy of the model is %.2f" %score)

 Accuracy of the model is 72.88

In [246]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                Model Name  R2_Score
7    CatBoosting Regressor  0.743915
6             XGBRegressor  0.736284
5  Random Forest Regressor  0.726162
3    K-Neighbors Regressor  0.578044
8       AdaBoost Regressor  0.549394
2                    Ridge  0.510443
0        Linear Regression  0.510440
4            Decision Tree  0.497669
1                    Lasso  0.441144

In [218]:
## Train multiple models in modular way 

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}
trained_model_list=[]
model_list=[]
r2_list=[]

for i in range(len(list(models))):                          # it will all model 
    model=list(models.values())[i]                          # in that models list wrt key & values we take first model values  wrt iteration of model 
    model.fit(X_train,y_train)                              # take every model and do fit on every model 

    #Make Predictions
    y_pred=model.predict(X_test)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)                   # we calling funt here 

    print(list(models.keys())[i])                            # print model keys , so it will print model name 
    model_list.append(list(models.keys())[i])               # we will append these model name with model_list

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 6.52668449832762
MAE: 5.170957985013024
R2 score 51.34237798107859
===================================


Lasso
Model Training Performance
RMSE: 6.997452261223104
MAE: 5.577518480043278
R2 score 44.069908434422445
===================================


Ridge
Model Training Performance
RMSE: 6.526685306525122
MAE: 5.170959433702186
R2 score 51.342365930558586
===================================


Elasticnet
Model Training Performance
RMSE: 7.035747508790441
MAE: 5.61871077160242
R2 score 43.456051408507435
===================================